### ISSUE TITLE
Make use of the issue function of GitHub

### ISSUE THREAD

**Issue by ZhouYou528** [yummycoding/weLoveFaceBook#1]
Divide the whole project into little parts, like developing a bunch of features, and set them in issues.
Also, report the bugs in issues.

**Comment by GrandStar** [comment]
We can add noStrictGenericChecks in the typescript. 
"compilerOptions": {
    "noStrictGenericChecks": true,
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [
      "hammerjs"
    ]
  },
And then ng-start problem will be solved.
