### ISSUE TITLE
Jobs left for zjunhao before sprint 3

### ISSUE THREAD

**Issue by zjunhao** [yummycoding/weLoveFaceBook#28]
1. e2e test for newly added functions
2. Add delete posts
3. Fetch all users' and users' friend posts at homepage
4. Probably add like, comment on posts

**Comment by zjunhao** [comment]
2 finished

**Comment by GrandStar** [comment]
need a connection for 3?

**Comment by zjunhao** [comment]
currently working on it, you can do comment backend on 4 if you want to help XD

**Comment by zjunhao** [comment]
3 finished
