### ISSUE TITLE
New Issue for time on post: still have problem

### ISSUE THREAD

**Issue by zjunhao** [yummycoding/weLoveFaceBook#32]
The time given by backend when create post is not correct (several hours delay), please help correct that

**Comment by zhuoru-li** [comment]
That is not an error. The time returned is international standard format date, not local time.

**Comment by zjunhao** [comment]
I've merged your test codes, solved some conflicts, please help check whether I wrongly deleted your things or not XD

**Comment by zjunhao** [comment]
All right, understand time problem

**Comment by zjunhao** [comment]
The posts send before and afterwards got the same time, need a fix on backend, cz we got time cling to post on backend

**Comment by zjunhao** [comment]
Resolved!
